### ISSUE TITLE
Long description too similar to Wikipedia

### ISSUE THREAD

**Issue by bentley** [standardebooks/rafael-sabatini_the-sea-hawk#2]
Wikipedia:

> The Sea Hawk is a 1915 novel by Rafael Sabatini. The story is set over the years 1588–1593 and concerns a retired Cornish seafaring gentleman, Sir Oliver Tressilian, who is villainously betrayed by a jealous half-brother. After being forced to serve as a slave on a galley, Sir Oliver is liberated by Barbary pirates. He joins the pirates, gaining the name "Sakr-el-Bahr" (the hawk of the sea), and swears vengeance against his brother.

Current long description:

> Sir Oliver Tressilian, a Cornish gentleman, is villainously betrayed by his jealous half-brother Lionel, who has him kidnapped and sold into slavery. After being forced to serve as a slave on a Spanish galley, Sir Oliver is liberated by Barbary pirates. He joins the pirates, gaining the name Sakr-El-Bahr—“The Hawk of the Sea”—and becomes the right-hand man to the pirates’ leader.

**Comment by acabal** [comment]
Thanks, a new long description has been committed to fix this.
